export const ROUTE_KEY = {
  Home: '/',
  Login: '/login',
  Register: '/register',
  Projects: '/projects',
  Board: '/board/:projectId',
  Setting: '/setting/:projectId',
  Activity: '/activity/:projectId',
  Tasks: '/tasks',
  TaskDetail: '/tasks/:taskId',
  People: '/people',
  Team: '/team',
  Invitation: '/invitation',
  NotFound: '/404',
};
